language: java
jdk: oraclejdk8

branches:
  only:
    - master

before_install:
  - chmod +x mvnw

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'

script: "./mvn clean build"



# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - lhy@guiving.com
